CREATE TABLE TEAM (
 TEAM_ID VARCHAR2(30) PRIMARY KEY,
 TEAM_NAME VARCHAR2(30) NOT NULL,
 LOCATION VARCHAR2(30) NOT NULL,
 MANAGER VARCHAR2(30) NOT NULL
);
COMMENT ON COLUMN TEAM.TEAM_ID IS '팀 아이디';
COMMENT ON COLUMN TEAM.TEAM_NAME IS '구단';
COMMENT ON COLUMN TEAM.LOCATION IS '연고지';
COMMENT ON COLUMN TEAM.MANAGER IS '감독';


CREATE TABLE MATCH (
 MATCH_ID VARCHAR2(30) PRIMARY KEY,
 HTEAM_ID VARCHAR2(30) NOT NULL,
 ATEAM_ID VARCHAR2(30) NOT NULL,
 HSCORE NUMBER NOT NULL,
 ASCORE NUMBER NOT NULL,
 MATCH_DAY DATE NOT NULL,
 
 FOREIGN KEY(HTEAM_ID) REFERENCES TEAM(TEAM_ID),
 FOREIGN KEY(ATEAM_ID) REFERENCES TEAM(TEAM_ID)
);
COMMENT ON COLUMN MATCH.MATCH_ID IS '경기 아이디';
COMMENT ON COLUMN MATCH.HTEAM_ID IS '홈팀';
COMMENT ON COLUMN MATCH.ATEAM_ID IS '어웨이팀';
COMMENT ON COLUMN MATCH.HSCORE IS '홈팀 점수';
COMMENT ON COLUMN MATCH.ASCORE IS '어웨이팀 점수';
COMMENT ON COLUMN MATCH.MATCH_DAY IS '경기날짜';

CREATE TABLE PLAYER (
 PL_ID VARCHAR2(30) PRIMARY KEY,
 TEAM_ID VARCHAR2(30) NOT NULL,
 PL_NAME VARCHAR2(30) NOT NULL,
 POSITION CHAR(3) NOT NULL CHECK( POSITION IN('FW','MF','DF') ),
 BACK_NUM NUMBER NOT NULL,
 
 FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID)
);
COMMENT ON COLUMN PLAYER.PL_ID IS '선수 아이디';
COMMENT ON COLUMN PLAYER.TEAM_ID IS '팀 아이디';
COMMENT ON COLUMN PLAYER.PL_NAME IS '선수이름';
COMMENT ON COLUMN PLAYER.POSITION IS '포지션';
COMMENT ON COLUMN PLAYER.BACK_NUM IS '등번호';

CREATE TABLE RECODE (
 RECODE_ID VARCHAR2(30) PRIMARY KEY,
 MATCH_ID VARCHAR2(30) NOT NULL,
 PL_ID VARCHAR2(30) NOT NULL,
 PLAY_TIME NUMBER NOT NULL,
 GOAL NUMBER NOT NULL,
 
 FOREIGN KEY (MATCH_ID) REFERENCES MATCH(MATCH_ID),
 FOREIGN KEY (PL_ID) REFERENCES PLAYER(PL_ID)
);
COMMENT ON COLUMN RECODE.RECODE_ID IS '기록 아이디';
COMMENT ON COLUMN RECODE.MATCH_ID IS '경기 아이디';
COMMENT ON COLUMN RECODE.PL_ID IS '선수 아이디';
COMMENT ON COLUMN RECODE.PLAY_TIME IS '출전시간';
COMMENT ON COLUMN RECODE.GOAL IS '득점';




































